server:
  port: 8080
  servlet:
    context-path: / # default path ??
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update # table ?? drop ? create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret:
            scope:
              - email
              - profile
          facebook:
            client-id: 
            client-secret: 
            scope:
              - email
              - public_profile # facebook 문서에서 확인
          naver: # OAuth2 client가 들고있는 provider가 아님 , provider id must be specified for client registration 'naver'
            client-id: 
            client-secret: 
            scope:
              - name
              - email
#              - profile-image
            # google, facebook, 트위터 등은 provider이기 때문에 밑에 정보들을 안적어줘도 됨(default)
            # naver는 provider가 아니기 때문에 적어줘야된다.
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # login ui
            token-uri: https://nid.naver.com/oauth2.0/token # token 받는 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보를 받는 uri
            user-name-attribute: response # 회원 정보를 json으로 받는데 response라는 값으로 네이버가 리턴해줌




