server:
  port: 8080
  servlet:
    context-path: / # default path ??
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
  jpa:
    hibernate:
      ddl-auto: update # table ?? drop ? create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 925329001522-7t3962d4hvhak466kc8vstb54s834oa8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


